module.exports = [
    {
        trackingNo: 1,
        timeIn: '2018-01-09 12:24:00', 
        timeOuts: '2018-01-09 15:05:00', 
        productName: 'Iphone 6', 
        client: 'Unionbank', 
        addres: '157 HV Dela Costa', 
        typeOfActivity: 'Onsite', 
        purposeOfVisit: 'troubleshoot', 
        activityPerformed:'checked if modules are up to date', 
        nextActivity: 'install updates', 
        recommendations:'no recommendations', 
        assignedSystemsEngineer: [['Tristian H. Cooley'], ['Angela G. Walker']],
        point_person: 'Kyle Lim' 
    },
    {
        trackingNo: 2,
        timeIn: '2018-01-10 13:32:00', 
        timeOuts: '2018-01-10 16:22:00',
        productName: 'Iphone 5s', 
        client: 'BPI', 
        addres: '15 Jupiter', 
        typeOfActivity: 'Remote', 
        purposeOfVisit: 'troubleshooting', 
        activityPerformed: 'check version of software', 
        nextActivity: 'install updates', 
        recommendations: 'no recommendations', 
        assignedSystemsEngineer: [['Kendal M. Floyd']],
        point_person:'JP Yap'
    },
    {
        trackingNo: 3,
        timeIn: '2018-01-17 13:32:00', 
        timeOuts: '2018-01-17 16:22:00',
        productName: 'Iphone 6s', 
        client: 'BPI', 
        addres: '15 Jupiter', 
        typeOfActivity: 'Onsite', 
        purposeOfVisit: 'troubleshooting', 
        activityPerformed: 'fixed home button', 
        nextActivity: 'checkup on customer', 
        recommendations: 'no recommendations', 
        assignedSystemsEngineer: [['Michael B. Jordan']],
        point_person:'Eddie Gurrero'
    },
    {
        trackingNo: 4,
        timeIn: '2018-01-19 13:32:00', 
        timeOuts: '2018-01-19 16:22:00',
        productName: 'Iphone X', 
        client: 'BPI', 
        addres: '15 Jupiter', 
        typeOfActivity: 'Implementation', 
        purposeOfVisit: 'dry the phone', 
        activityPerformed: 'dried up phone', 
        nextActivity: 'checkup on customer', 
        recommendations: 'no recommendations', 
        assignedSystemsEngineer: [['Waylon A. Dalton']],
        point_person:'Randy Orton'
    },
    {
        trackingNo: 5,
        timeIn: '2018-01-19 14:30:00', 
        timeOuts: '2018-01-19 16:40:00',
        productName: 'Iphone 5s', 
        client: 'Meralco', 
        addres: 'Pasig City', 
        typeOfActivity: 'POC', 
        purposeOfVisit: 'backup', 
        activityPerformed: 'backup phone', 
        nextActivity: 'checkup on customer', 
        recommendations: 'no recommendations', 
        assignedSystemsEngineer: [['Waylon A. Dalton']],
        point_person:'John Doe'
    },
    {
        trackingNo: 6,
        timeIn: '2018-01-23 10:30:00', 
        timeOuts: '2018-01-23 13:40:00',
        productName: 'Macbook Pro 2016', 
        client: 'BPI', 
        addres: '15 Jupiter', 
        typeOfActivity: 'POC', 
        purposeOfVisit: 'backup pc', 
        activityPerformed: 'backed up pc', 
        nextActivity: 'checkup on customer', 
        recommendations: 'no recommendations', 
        assignedSystemsEngineer: [['Waylon A. Dalton']],
        point_person:'Mary Mary'
    },
    {
        trackingNo: 007,
        timeIn: '2018-01-25 10:30:00', 
        timeOuts: '2018-01-25 13:40:00',
        productName: 'Galaxy Note8', 
        client: 'Ocean Park', 
        addres: 'Manila Bay', 
        typeOfActivity: 'Onsite', 
        purposeOfVisit: 'fix crack', 
        activityPerformed: 'new screen', 
        nextActivity: 'checkup on customer', 
        recommendations: 'no recommendations', 
        assignedSystemsEngineer: [['Eddie F. Randolph'], ['Justine B. Henderson']],
        point_person:'Gary T. Snail'
    },
    {
        trackingNo: 8, 
        timeIn: '2018-01-25 14:30:00', 
        timeOuts: '2018-01-25 15:40:00',
        productName: 'French Door', 
        client: 'BPI', 
        addres: '15 Jupiter', 
        typeOfActivity: 'Remote', 
        purposeOfVisit: 'fix fridge', 
        activityPerformed: 'now cooling', 
        nextActivity: 'checkup on customer', 
        recommendations: 'no recommendations', 
        assignedSystemsEngineer: [['Mathias D. Little']],
        point_person:'James Young'
    },
    {
        trackingNo: 9,
        timeIn: '2018-01-29 14:30:00', 
        timeOuts: '2018-01-29 15:40:00',
        productName: 'Iphone 5s', 
        client: 'BPI', 
        addres: '15 Jupiter', 
        typeOfActivity: 'Remote', 
        purposeOfVisit: 'fix phone', 
        activityPerformed: 'now working', 
        nextActivity: 'checkup on customer', 
        recommendations: 'no recommendations', 
        assignedSystemsEngineer: [['Tristan H. Cooley']],
        point_person:'Derick Cole'
    },
    {
        trackingNo: 10,
        timeIn: '2018-02-01 14:30:00', 
        timeOuts: '2018-02-01 15:40:00',
        productName: 'Top Mount Freezer', 
        client: 'Unionbank', 
        addres: '157 HV Dela Costa', 
        typeOfActivity: 'Onsite', 
        purposeOfVisit: 'fix fridge', 
        activityPerformed: 'now cooling', 
        nextActivity: 'checkup on customer', 
        recommendations: 'no recommendations', 
        assignedSystemsEngineer: [['Abdullah C. Langston']],
        point_person:'Kyrie Irving'
    },
    {
        trackingNo: 11,
        timeIn: '2018-01-29 11:30:00', 
        timeOuts: '2018-01-29 16:40:00',
        productName: 'Nike Epic React Flyknit', 
        client: 'BPI', 
        addres: '15 Jupiter', 
        typeOfActivity: 'Onsite', 
        purposeOfVisit: 'put together', 
        activityPerformed: 'now walkable', 
        nextActivity: 'checkup on customer', 
        recommendations: 'no recommendations', 
        assignedSystemsEngineer: [['Bronson K. Robinson']],
        point_person:'Usain Bolt'
    }
];