module.exports = [
    {
        vendorCaseId: 'JF1',
        dateIdCreated: '01/08/2018',
        dateRaised: '01/07/2018',
        caseTitle: 'Attend to failure of backup',
        caseDescription: 'troubleshoot',
        severity: 1,
        vendor: 'Apple',
        customer: 'Unionbank',
        productName: 'Iphone 6',
        contact_person: 'Mareeah Koochenera',
        systemsEngineerLead: 'Lia E. Shelton',
        case_status: 'Ongoing'
    },
    {
        vendorCaseId: 'JF2',
        dateIdCreated: '01/09/2018',
        dateRaised: '01/08/2018',
        caseTitle: 'Fix server for backup',
        caseDescription: 'install updates',
        severity: 1,
        vendor: 'Apple',
        customer: 'BPI',
        productName: 'Iphone 5s',
        contact_person: 'Garrosh',
        systemsEngineerLead: 'Michael B. Jordan',
        case_status: 'Ongoing'
    },
    {
        vendorCaseId: 'JF3',
        dateIdCreated: '01/15/2018',
        dateRaised: '01/13/2018',
        caseTitle: 'Home button broken',
        caseDescription: 'not working on press',
        severity: 1,
        vendor: 'Apple',
        customer: 'BPI',
        productName: 'Iphone 6s',
        contact_person: 'Garrosh',
        systemsEngineerLead: 'Lia E. Shelton',
        case_status: 'Pending (Client)'
    },
    {
        vendorCaseId: 'JF4',
        dateIdCreated: '01/17/2018',
        dateRaised: '01/16/2018',
        caseTitle: 'Wet Phone',
        caseDescription: 'not working',
        severity: 1,
        vendor: 'Apple',
        customer: 'BPI',
        productName: 'Iphone X',
        contact_person: 'Lich King',
        systemsEngineerLead: 'Justine B. Henderson',
        case_status: 'Ongoing'
    },
    {
        vendorCaseId: 'JF5',
        dateIdCreated: '01/18/2018',
        dateRaised: '01/17/2018',
        caseTitle: 'Clean backups',
        caseDescription: 'cleaning',
        severity: 1,
        vendor: 'Apple',
        customer: 'Meralco',
        productName: 'Iphone 5s',
        contact_person: 'Hans Yim',
        systemsEngineerLead: 'Michael B. Jordan',
        case_status: 'Pending (Glo-cal)'
    },
    {
        vendorCaseId: 'JF6',
        dateIdCreated: '01/22/2018',
        dateRaised: '01/21/2018',
        caseTitle: 'Fix server for backup',
        caseDescription: 'install updates',
        severity: 1,
        vendor: 'Apple',
        customer: 'BPI',
        productName: 'Macbook Pro 2016',
        contact_person: 'Garrosh',
        systemsEngineerLead: 'Abdullah C. Langston',
        case_status: 'Pending (Client)'
    },
    {
        vendorCaseId: 'JF7',
        dateIdCreated: '01/23/2018',
        dateRaised: '01/22/2018',
        caseTitle: 'Change screen',
        caseDescription: 'remove crack',
        severity: 1,
        vendor: 'Samsung',
        customer: 'Ocean Park',
        productName: 'Galaxy Note8',
        contact_person: 'Seal King',
        systemsEngineerLead: 'Michael B. Jordan',
        case_status: 'Ongoing'
    },
    {
        vendorCaseId: 'JF8',
        dateIdCreated: '01/25/2018',
        dateRaised: '01/24/2018',
        caseTitle: 'Cooling not working',
        caseDescription: 'hot',
        severity: 2,
        vendor: 'Samsung',
        customer: 'BPI',
        productName: 'French Door',
        contact_person: 'Garrosh',
        systemsEngineerLead: 'Ricardo L. Kaufman',
        case_status: 'Ongoing'
    },
    {
        vendorCaseId: 'JF9',
        dateIdCreated: '01/26/2018',
        dateRaised: '01/26/2018',
        caseTitle: 'trouble',
        caseDescription: 'install updates',
        severity: 1,
        vendor: 'Apple',
        customer: 'BPI',
        productName: 'Iphone 5s',
        contact_person: 'Garrosh',
        systemsEngineerLead: 'Michael B. Jordan',
        case_status: 'Ongoing'
    },
    {
        vendorCaseId: 'JF10',
        dateIdCreated: '01/27/2018',
        dateRaised: '01/26/2018',
        caseTitle: 'money is lost',
        caseDescription: 'finding money',
        severity: 1,
        vendor: 'Samsung',
        customer: 'Unionbank',
        productName: 'Top Mount Freezer',
        contact_person: 'Banker Dude',
        systemsEngineerLead: 'Ruth I. Foster',
        case_status: 'Pending (Glo-cal)'
    },
    {
        vendorCaseId: 'JF11',
        dateIdCreated: '01/28/2018',
        dateRaised: '01/27/2018',
        caseTitle: 'Buy shoes',
        caseDescription: 'install updates',
        severity: 1,
        vendor: 'Nike',
        customer: 'BPI',
        productName: 'Nike Epic React Flyknit',
        contact_person: 'Garrosh',
        systemsEngineerLead: 'Ruth I. Foster',
        case_status: 'Ongoing'
    },
    {
        vendorCaseId: 'JF12',
        dateIdCreated: '02/03/2018',
        dateRaised: '02/03/2018',
        caseTitle: 'Fix server for backup',
        caseDescription: 'install updates',
        severity: 1,
        vendor: 'Apple',
        customer: 'Unionbank',
        productName: 'Iphone 5s',
        contact_person: 'Banker Dufe',
        systemsEngineerLead: 'Michael B. Jordan',
        case_status: 'Ongoing'
    },
    {
        vendorCaseId: 'JF13',
        dateIdCreated: '02/04/2018',
        dateRaised: '02/03/2018',
        caseTitle: 'Fix server for backup',
        caseDescription: 'install updates',
        severity: 1,
        vendor: 'Nike',
        customer: 'BPI',
        productName: 'Nike Zoom Fly',
        contact_person: 'Garrosh',
        systemsEngineerLead: 'Ricardo L. Kaufman',
        case_status: 'Pending (Glo-cal)'
    },
    {
        vendorCaseId: 'JF14',
        dateIdCreated: '02/05/2018',
        dateRaised: '02/03/2018',
        caseTitle: 'Restrictag',
        caseDescription: 'Did nothing',
        severity: 3,
        vendor: 'Microsoft',
        customer: 'Meralco',
        productName: 'Visual Studio Code',
        contact_person: 'Hans Yim',
        systemsEngineerLead: 'Michael B. Jordan',
        case_status: 'Ongoing'
    },
    {
        vendorCaseId: 'JF15',
        dateIdCreated: '02/06/2018',
        dateRaised: '02/6/2018',
        caseTitle: 'Visual Studio Community',
        caseDescription: 'not compiling',
        severity: 1,
        vendor: 'Apple',
        customer: 'BPI',
        productName: 'Iphone 5s',
        contact_person: 'Garrosh',
        systemsEngineerLead: 'Michael B. Jordan',
        case_status: 'Ongoing'
    },
    {
        vendorCaseId: 'JF16',
        dateIdCreated: '02/08/2018',
        dateRaised: '02/06/2018',
        caseTitle: 'Fix server for backup',
        caseDescription: 'install updates',
        severity: 1,
        vendor: 'Apple',
        customer: 'Ocean Park',
        productName: 'Iphone 5s',
        contact_person: 'Garrosh',
        systemsEngineerLead: 'Michael B. Jordan',
        case_status: 'Ongoing'
    },
    {
        vendorCaseId: 'JF17',
        dateIdCreated: '03/03/2018',
        dateRaised: '03/03/2018',
        caseTitle: 'Remove blurry',
        caseDescription: 'blur',
        severity: 1,
        vendor: 'Samsung',
        customer: 'Meralco',
        productName: 'Premium UHD TV',
        contact_person: 'Hans Yim',
        systemsEngineerLead: 'Ruth I. Foster',
        case_status: 'Ongoing'
    }
];