module.exports = [
    {
        vendorCaseId: 'JF1',
        dateIdCreated: '01/08/2018',
        dateRaised: '01/07/2018',
        caseTitle: 'Attend to failure of backup',
        caseDescription: 'troubleshoot',
        severity: 1,
        vendor: 'Veritas',
        customer: 'Unionbank',
        productName: 'Multi-Cloud',
        systemsEngineerLead: 'Jefferson',
        assignedAccountManager: 'Mei',
        assignedSystemsEngineer: ['Isaiah Solomon', 'Aaron Hernandez'],
        case_status: 'Ongoing'
    },
    {
        vendorCaseId: 'JF2',
        dateIdCreated: '03/08/2018',
        dateRaised: '03/07/2018',
        caseTitle: 'Fix server for backup',
        caseDescription: 'install updates',
        severity: 1,
        vendor: 'Symantec',
        customer: 'BPI',
        productName: 'Secure Web Gateway',
        systemsEngineerLead: 'Jeffrey',
        assignedAccountManager: 'Maan',
        assignedSystemsEngineer: ['Isaiah Solomon'],
        case_status: 'Resolved'
    },
    {
        vendorCaseId: 'JF3',
        dateIdCreated: '04/04/2018',
        dateRaised: '04/01/2018',
        caseTitle: 'Error 404',
        caseDescription: 'fix error',
        severity: 2,
        vendor: 'Veritas',
        customer: 'BPI',
        productName: 'Secure Web Gateway',
        systemsEngineerLead: 'Jefferson',
        assignedAccountManager: 'Mei',
        assignedSystemsEngineer: ['Isaiah Solomon'],
        case_status: 'Ongoing'
    },
    {
        vendorCaseId: 'JF4',
        dateIdCreated: '04/07/2018',
        dateRaised: '04/06/2018',
        caseTitle: 'Fix server for backup',
        caseDescription: 'install updates',
        severity: 2,
        vendor: 'Symantec',
        customer: 'Unionbank',
        productName: 'Multi-Cloud',
        systemsEngineerLead: 'Oliver',
        assignedAccountManager: 'Maan',
        assignedSystemsEngineer: ['Aaron Hernandez'],
        case_status: 'Pending (Glo-cal)'
    },
    {
        vendorCaseId: 'JF5',
        dateIdCreated: '05/11/2018',
        dateRaised: '05/09/2018',
        caseTitle: 'Attend to failure of backup',
        caseDescription: 'troubleshoot',
        severity: 2,
        vendor: 'Veritas',
        customer: 'BPI',
        productName: 'Secure Web Gateway',
        systemsEngineerLead: 'Jeffrey',
        assignedAccountManager: 'Mei',
        assignedSystemsEngineer: ['John Jenkins'],
        case_status: 'Pending (Client)'
    },
    {
        vendorCaseId: 'JF6',
        dateIdCreated: '05/11/2018',
        dateRaised: '05/09/2018',
        caseTitle: 'Attend to failure of backup',
        caseDescription: 'troubleshoot',
        severity: 2,
        vendor: 'Veritas',
        customer: 'BPI',
        productName: 'Secure Web Gateway',
        systemsEngineerLead: 'Jeffrey',
        assignedAccountManager: 'Mei',
        assignedSystemsEngineer: ['Aaron Hernandez'],
        case_status: 'Pending (Client)'
    },
];